---
title: "P3 Data Preparation"
author: "ALS"
date: "2023-04-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading data and packages
```{r}
library(tidyverse)
library(lubridate)

crime <- read.csv("/Users/annsofo/Documents/UVA/Spring 2023/DS Project Course/Project 3/Crime_Data.csv")

View(crime)
```

# Adding useful time variables
```{r}

crime1 <- crime %>%
  select(DateReported, Offense) %>%
  mutate(DateTime = lubridate::as_datetime(DateReported)) %>%
  mutate(Date = format(DateTime,'%Y-%m-%d')) %>%
  mutate(Year = format(DateTime,'%Y')) %>%
  mutate(Month = format(DateTime,'%B')) %>%
  mutate(Day = format(DateTime, '%d')) %>%
  mutate(HourMin = format(DateTime,'%H:%M')) %>%
  mutate(Hour = format(DateTime,'%H')) 

# adding weekday

crime2 <- crime1 %>%
  mutate(day_of_week = lubridate::wday(Date, week_start=6))
         
crime2 <- crime2 %>%
  mutate(Weekday = case_when(day_of_week == 1 ~ "Mon",
                                day_of_week == 2 ~ "Tues",
                                day_of_week == 3 ~ "Wed",
                                day_of_week == 4 ~ "Thurs",
                                day_of_week == 5 ~ "Fri",
                                day_of_week == 6 ~ "Sat",
                                day_of_week == 7 ~ "Sun"))


# No unfiltered date col
crime3 <- crime2 %>%
  select(-c(DateReported, DateTime, HourMin, Day, day_of_week))

View(crime3)

```

# Adding number of crimes by data variable
```{r}
crime4 <- crime3 %>%
  group_by(Date) %>%
  mutate(NumCrimes = n())

View(crime4)
```

# Group A vs. Group B crimes
```{r}
table(crime3$Offense)

# Suspicious Person, Suspicious Activity, Assault


crime4 <- fct_collapse(crime4$Offense,
                            Assault = c("Assault Aggravated","Assault Simple","Assault Intimidation",
                                        `Suspicious Persons/Activity` = c("Suspicious Person", "Suspicious Activity")))

group_a <- c("Assault","Shots Fired/Illegal Hunting","Suspicious Persons/Activity")

crime5 <- crime4 %>%
  mutate(GroupA = case_when((Offense %in% group_a) == TRUE ~ 1, 
                            TRUE ~ 0),
         GroupB = case_when(!(Offense %in% group_a) == TRUE ~ 1, 
                            TRUE ~ 0))

crime6 <- crime5 %>%
  mutate(Assault = case_when((Offense == "Assault") == TRUE ~ 1, 
                            TRUE ~ 0),
         Suspicious_Persons_Activity = case_when((Offense == "Suspicious Persons/Activity") == TRUE ~ 1, 
                            TRUE ~ 0),
         ShotsFired_IllegalHunting = case_when((Offense == "Shots Fired/Illegal Hunting") == TRUE ~ 1, 
                            TRUE ~ 0))
         

View(crime6)

```

# Removing 2023 and creating new datasets
```{r}
colnames(crime6)

# re-ordering columns
crime6 <- crime6[,c("Offense","Date","Year","Month","Hour","Weekday",
                    "GroupA","Assault","ShotsFired_IllegalHunting",
                    "Suspicious_Persons_Activity","GroupB",
                    "NumCrimes")]

crime_wo_2023 <- crime6 %>%
  filter(Year != 2023)

write.csv(crime_wo_2023, "/Users/annsofo/Documents/UVA/Spring 2023/DS Project Course/Project 3/crime_wo_2023.csv")

crime_2023 <- crime6 %>%
  filter(Year == 2023)

write.csv(crime_2023, "/Users/annsofo/Documents/UVA/Spring 2023/DS Project Course/Project 3/crime_2023.csv")

```
# Periodogram
```{r}

ts_data <- ts(crime6$NumCrimes)

crime_pg <- spec.pgram(ts_data,spans=9,demean=T,log='no')
crime_spec <- data.frame(freq=crime_pg$freq, spec=crime_pg$spec)
  
ggplot(crime_spec) + geom_line(aes(x=freq,y=spec)) +
  ggtitle("Smooth PG of Crime Data") + xlab("Frequency") +
  ylab("Squared Amplitude")


```

